---
#Outputs
# creating EC2 instance
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0b72821e2f351e396
      InstanceType: t2.micro

Outputs:
    RegionName: #Output name, could be anything in here
        Description: Region name the ec2 is being deployed
        Value: !Ref "AWS::Region" # "AWS::Region" is a pseudo parameter
        #We are outputting the region we are deploying this stack
    Az:
        Description: Az zone from the ec2 instance
        Value: !GetAtt MyInstance.AvailabilityZone #using !GetAtt for retriving AZ infor from the instance