---
# creating EC2 instance

Parameters:
  EnvironmentName:
    Description: EnviromentName
    Type: String
    AllowedValues: [development, production]
    ConstraintDescription: must be development or production

  instanceTypes:
    Description: Instance Type
    Type: String
    AllowedValues: [t2.micro, t2.small]

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0b72821e2f351e396
      InstanceType: !Ref instanceTypes


Rules:
  testInstanceType:
    RuleCondition: !Equals 
      - !Ref EnvironmentName
      - development
    Assertions:
      - Assert:
          'Fn::Contains':
            - - t2.micro
            - !Ref InstanceType
        AssertDescription: 'For a test environment, the instance type must be t2.micro'
  prodInstanceType:
    RuleCondition: !Equals 
      - !Ref Environment
      - production
    Assertions:
      - Assert:
          'Fn::Contains':
            - - t2.small
            - !Ref InstanceType
        AssertDescription: 'For a production environment, the instance type must be t2.small'