---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0b72821e2f351e396
      InstanceType: t2.micro
      UserData: #Defining the user data paramenter
        Fn::Base64: | #using the function base64 for converting string to it's base 64 representation
          #!bin/bash
          mkdir /etc/created_folder
          echo "This file has been created through the user data section" > /etc/created_folder/file.txt

#The user data will the first commend the EC2 instance will run at the first launch